version: '3'
services:
  mysql5.6:
    image: mysql:5.6
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    # MariaDB >= 10.0.12 doesn't enable Performance Schema by default so we need to do it manually
    # https://mariadb.com/kb/en/mariadb/performance-schema-overview/#activating-the-performance-schema
    command: --performance-schema --secure-file-priv=""
    volumes:
      - ./testdata/schema/:/docker-entrypoint-initdb.d/:rw
  mysql5.7:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    # MariaDB >= 10.0.12 doesn't enable Performance Schema by default so we need to do it manually
    # https://mariadb.com/kb/en/mariadb/performance-schema-overview/#activating-the-performance-schema
    command: --performance-schema --secure-file-priv=""
    volumes:
      - ./testdata/schema/:/docker-entrypoint-initdb.d/:rw
  mysql8.0:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    # MariaDB >= 10.0.12 doesn't enable Performance Schema by default so we need to do it manually
    # https://mariadb.com/kb/en/mariadb/performance-schema-overview/#activating-the-performance-schema
    command: --performance-schema --secure-file-priv=""
    volumes:
      - ./testdata/schema/:/docker-entrypoint-initdb.d/:rw
